Venafi/vcert

example/vars.go, pkg/certificate/certificate.go, pkg/venafi/tpp/connector.go, pkg/venafi/tpp/connector_test.go, pkg/venafi/tpp/tpp.go
also in this pull request there are few small fixes for different part of vcert
=> Trust bundle example

pkg/endpoint/endpoint.go, pkg/endpoint/endpoint_test.go
Don't change certificates fields if the're unlocked.
=> Don't change certificates fields if the're unlocked.

pkg/venafi/cloud/cloud.go
=> add trust bundle for cloud as requested in issue #39

pkg/endpoint/endpoint.go, pkg/venafi/cloud/cloud.go, pkg/venafi/cloud/connector.go, pkg/venafi/fake/connector.go, pkg/venafi/tpp/connector.go, pkg/venafi/tpp/tpp.go
=> Http custom client

examples/simple-cli/main.go, examples/simple-cli/main_test.go
=> add example for ListCertificates

cmd/vcert/validators.go
=> Fix bug about rading  --key-password from file

pkg/venafi/tpp/connector.go
=> fix code style

cmd/vcert/commands.go, cmd/vcert/result_writer.go, pkg/venafi/tpp/connector.go
=> Renew cert printing

aruba/features/step_definitions/actions.rb, pkg/endpoint/endpoint.go, pkg/endpoint/endpoint_test.go, pkg/venafi/cloud/certificatePolicies.go, pkg/venafi/cloud/connector.go, pkg/venafi/cloud/connector_test.go, pkg/venafi/tpp/connector_test.go, pkg/venafi/tpp/tpp.go
=> Recommended zone values

cmd/vcert/args.go, cmd/vcert/commands.go, cmd/vcert/flags.go
Fix for https://github.com/Venafi/vcert/issues/120
=> Make --no-retire option work for revoke action

aruba/features/step_definitions/actions.rb, aruba/features/step_definitions/endpoints.rb, aruba/features/step_definitions/my_steps.rb, cmd/vcert/commands.go, cmd/vcert/flags.go
@angelmoo @rvelaVenafi Sorry, I was lazy and didn't run the cucumber tests when I did https://github.com/Venafi/vcert/pull/139 :pensive:  This fixes what I missed along with a bit of other housekeeping in that area.  I ran our Jenkins job against this branch and it passed (1089).
=> Fix cucumber tests

aruba/Dockerfile, aruba/cucumber.sh
added the new parameters TPP_IP and TPP_CN to the docker run command to pass the values of the IP and CN of the virtualized TPP instance.
=> added the new parameters TPP_IP and TPP_CN 

aruba/Dockerfile, aruba/cucumber.sh, pkg/venafi/cloud/connector.go
Added loop to wait for certificate retrieval.
Fixed cucumber tests looped execution.
=> Vc 9916 fix

cmd/vcert/args.go, cmd/vcert/commands.go, cmd/vcert/config.go, cmd/vcert/flags.go, cmd/vcert/main.go, cmd/vcert/validators.go, pkg/certificate/certificate.go, pkg/certificate/sshCADetails.go, pkg/endpoint/endpoint.go, pkg/policy/constants.go, pkg/util/constants.go, pkg/venafi/cloud/connector.go, pkg/venafi/fake/connector.go, pkg/venafi/tpp/connector.go, pkg/venafi/tpp/connector_test.go, pkg/venafi/tpp/sshCertUtils.go, pkg/venafi/tpp/tpp.go
added a new command(sshgetconfig) to get the CA public key and the default principals
updated structures to handle changes on the ssh request/retrieve certificate responses.
=> Tpp213 ssh changes

cmd/vcert/flags.go
Closes: https://github.com/Venafi/vcert/issues/190
=> Adds flag to pass the trust bundle on sshgetconfig command for TPP

cmd/vcert/flags.go, pkg/endpoint/endpoint.go
-removed no-prompt flag and removed unnecessary error message
=> minor changes requested on testing SSH new feature

Dockerfile, Makefile
Updated make file instructions to allow code coverage to be reported
=> Enhancements for code coverage

pkg/certificate/certificate.go, pkg/endpoint/endpoint.go, pkg/venafi/cloud/connector.go, pkg/venafi/fake/connector.go, pkg/venafi/tpp/connector.go, pkg/venafi/tpp/tpp.go
added requested functionality under ticket: #203
=> added requested functionality under ticket: #203

pkg/venafi/cloud/connector.go, pkg/venafi/cloud/connector_test.go, pkg/venafi/tpp/connector.go
Disabling the re-enabled test cloud/connector_test.TestGetPolicy for development purposes and fix to work with invalid user
=> Re-disable cloud/connector_test.TestGetPolicy and fix to work with invalid user 

pkg/venafi/tpp/connector.go
Adding code to avoid nil pointer at the moment to get an Identity
=> Avoid possible nil pointer tpp.getIdentity method

cmd/vcert/flags.go, cmd/vcert/utils.go, cmd/vcert/validators.go
=> Avoid -u flag as mandatory for VaaS user register

pkg/venafi/fake/connector.go
Updates code so golangci-lint version 1.47.3 (latest) runs happy
=> Updates code to be compliant for golangci-lint version 1.47.3

pkg/endpoint/endpoint.go, pkg/venafi/cloud/connector.go, pkg/venafi/fake/connector.go, pkg/venafi/tpp/connector.go, pkg/venafi/tpp/connector_test.go, pkg/venafi/tpp/tpp.go
=> Revert "Add user Identity  to TPP Connector and exposed the RetrieveSystemVersion() function"

pkg/endpoint/endpoint.go, pkg/venafi/cloud/connector.go, pkg/venafi/fake/connector.go, pkg/venafi/tpp/connector.go, pkg/venafi/tpp/connector_test.go, pkg/venafi/tpp/tpp.go
=> Add user Identity  to TPP Connector and exposed the RetrieveSystemVersion() function

pkg/venafi/tpp/connector_test.go
fmt.Errorf should have been t.Errorf
=> Fix error in test

README-CLI-CLOUD.md, README-CLI-PLATFORM.md
Ability to install via homebrew.
=> Reflecting brew support in docs and some docs enhancements

README-PLAYBOOK.md, README.md, cmd/vcert/playbook.go, examples/playbook/sample.capi.yaml, examples/playbook/sample.cert-auth.yaml, examples/playbook/sample.jks.yaml, examples/playbook/sample.multi.yaml, examples/playbook/sample.pem.yaml, examples/playbook/sample.pkcs12.yaml, examples/playbook/sample.tlspc.yaml, pkg/playbook/app/installer/capi.go, pkg/playbook/app/installer/crypto.go, pkg/playbook/app/installer/jks.go, pkg/playbook/app/installer/pem.go, pkg/playbook/app/installer/pkcs12.go, pkg/playbook/app/parser/reader.go, pkg/playbook/app/service/service.go, pkg/playbook/app/service/tokenService.go, pkg/playbook/app/vcertutil/helper.go, pkg/playbook/app/vcertutil/vcertutil.go, pkg/playbook/util/capistore/helper.go, pkg/playbook/util/capistore/powershell.go, pkg/playbook/util/cmdexec.go, pkg/playbook/util/cmdexec_windows.go, pkg/playbook/util/filehelper.go
Fixed loggers to properly set log fields
=> feat(playbook): Added examples and README

Makefile, cmd/vcert/commands.go, cmd/vcert/config.go, cmd/vcert/result_writer.go, cmd/vcert/utils.go, cmd/vcert/validators.go, config.go, pkg/playbook/app/vcertutil/helper.go, pkg/policy/policyUtils.go, pkg/venafi/cloud/cloud.go, pkg/venafi/cloud/connector.go, pkg/venafi/tpp/connector.go, pkg/venafi/tpp/tpp.go, test/fixtures.go
Fixes all linter issues reported
Closes VC-25271
=> Linter issues

Makefile
=> feat(pipeline): Fixed release target

Makefile
=> fix(version): Fixed issue with version not showing

pkg/playbook/app/vcertutil/vcertutil.go
Fixed issue with local-generated CSR, where it attempted to retrieve the private key from the Venafi platform
Closes VC-25639
=> fix(local-csr): Fixed issue 330

go.mod
Closes https://venafi.atlassian.net/browse/VC-24605, https://venafi.atlassian.net/browse/VC-24606, https://venafi.atlassian.net/browse/VC-24607 and https://venafi.atlassian.net/browse/VC-24608
=> Feat: Add missed required mod

pkg/venafi/firefly/connector.go
updating the Authentication process for Firefly connector so this will try to get Authorization if that was not provided
=> Feat: Update authentication process for Firefly connector.

pkg/playbook/app/vcertutil/vcertutil.go, pkg/venafi/firefly/connector.go
Added nil validation for auth object
=> feat(firefly): Minor changes in Authenticate function

.gitignore, aruba/Dockerfile, aruba/cucumber.sh, aruba/features/firefly/firefly.feature, aruba/features/step_definitions/actions.rb, aruba/features/step_definitions/endpoints.rb, aruba/features/step_definitions/my_steps.rb
closes [VC-25799](https://venafi.atlassian.net/browse/VC-25799)
[VC-25799]: https://venafi.atlassian.net/browse/VC-25799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cucumber tests for certificate enrollment with Firefly

aruba/features/config/basic.feature, aruba/features/step_definitions/my_steps.rb, aruba/features/support/aruba.rb
- Fixes expected message output
- Adds test for case when current 3 platforms are defined in INI file
- Fixes issue when reading output from JSON format
=> Fixes cucumber tests

cmd/vcert/flags.go
Removing that the audience flag accept multiple values.
=> Update Audience flag description

pkg/playbook/app/service/service.go
Fixes issues reported internally while testing.
=> Use actual certificate serial instead of subject serial

pkg/certificate/certificate.go, pkg/certificate/request.go, pkg/venafi/firefly/connector.go, pkg/venafi/firefly/firefly.go, pkg/venafi/firefly/fireflyUtil.go
Fix that the default value for `--key-type ecdsa` must be `P256`
=> Feat: Fix support for default key-curve

pkg/playbook/app/installer/capi.go, pkg/playbook/app/service/service.go
Fixes the issue of empty location in logs when a CAPI installation runs
=> Capi log fix

Makefile, pkg/venafi/firefly/connector_test.go, pkg/venafi/firefly/devAuthStatus.go, pkg/venafi/firefly/deviceFlow.go, pkg/venafi/firefly/identityProviderServer_test.go
- Add unit tests for firefly.Connector.Authorize()
- Fix a bug getting the AuthStatus for DevFlowGrant.
Closes VC-25642
=> Feat: Add unit tests for Firefly GetCred.

aruba/features/playbook/steps_definitions/my_steps.rb, aruba/features/playbook/support/aruba.rb, pkg/venafi/cloud/connector_test.go
- adds SAN DNS name for ED25519 cert-key pair failing tests
=> Fix: Issue with ED25519 cert-key pair failing tests

go.mod, go.sum, pkg/endpoint/endpoint.go, pkg/venafi/cloud/connector.go, pkg/venafi/cloud/connectorPolicy.go, pkg/venafi/cloud/connectorSSH.go, pkg/venafi/cloud/connector_test.go, pkg/venafi/cloud/search.go
=> Fixes to support service account authentication in TLSPC

aruba/features/enroll/enroll-with-csr.feature, aruba/features/firefly/firefly.feature, aruba/features/step_definitions/my_steps.rb, cmd/vcert/config.go, cmd/vcert/envVars.go, cmd/vcert/main_test.go, cmd/vcert/validators.go, cmd/vcert/validatorsCloud.go, cmd/vcert/validatorsFirefly.go, cmd/vcert/validatorsTPP.go
=> feat(svc-account-playbook): Test fixes for service-account authentication

cmd/vcert/commands.go
Fixes an issue where VCP token expiration was not properly outputted to the user
=> fix(vcp-token-expiration): Fixes issue with VCP token expiration

examples/provisionWithServiceAccount/main.go, pkg/util/utils.go, pkg/venafi/cloud/connector.go, pkg/websocket/websocket.go
Adds support for usage of Service Account Auth with Certificate Provisioning in VCert SDK
=> VCert SDK - Certificate Provisioning with Service Account Auth

go.sum, pkg/playbook/app/vcertutil/vcertutil.go
vcert playbook - fixes issue when default time is not set, it was taking 30 secs instead of 180, also added chance to set own timeout
=> vcert playbook - fixes issue with timeout

aruba/features/provision/cloudkeystore/provision_cloudkeystore.feature, aruba/features/provision/cloudkeystore/steps_definitions/my_steps.rb, cmd/vcert/cmdCloudKeystores.go, cmd/vcert/cmdHelper.go, cmd/vcert/flags.go
- Fixes bug that would print warning log, even if platform flag is set properly. 
- Fixes description for platform flag
=> BUGFIX: Fixes warning behavior when Platform flag is set

pkg/venafi/cloud/cloud.go
=> fix: use valid str index
