client.go
config.go

When using custom clients we still ran into authentication failures when using the Client from config feature. This can be recreated by putting VCert TPP behind anything that will require a custom client. Or in the case that we use a test instance with a certificate that doesn't validate and disable certificate verification for our TPP instance.
This just adds the ability to set a client in the config so it is set before the call to `connector.Authenticate`

Add http.Client as an option for construction of a new client

---

pkg/endpoint/endpoint.go

While debugging my tests I found the `checkStringByRegexp` and `isComponentValid` had named return parameters but then used a `return true` which specifically set the return value.
I have removed the name from the return parameters to have more consistent returns.

Remove mixed use of named and non-named return parameters

---

pkg/venafi/fake/connector.go

Currently there is no policy set in the zone configuration in fake which will fail validation later on.
When updating the module i found our tests to be failing on validating the CSR.
We use the fake connector as client in our tests
https://github.com/jetstack/cert-manager/blob/master/pkg/internal/venafi/sign_test.go#L197 
From which we use `client.ReadZoneConfiguration()` to get the zone configuration and then validate the CSR, however in the fake package it seems to not pass through the fake policy to the zone configuration.
I added this to `ReadZoneConfiguration` and everything works fine again.
Feedback welcome, hope I understood why this failed correct :smiley:

Set policy on fake ReadZoneConfiguration()

---

cmd/vcert/validators.go
pkg/endpoint/endpoint.go
pkg/venafi/cloud/cloud.go
pkg/venafi/cloud/connector.go
pkg/venafi/cloud/connector_test.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/tpp.go

- Switched import for Cloud from /v1/discovery to /v1/certificaterequests/externalissuance/certificates
- Added source application tagging for certificates enrolled and imported with Cloud

Source Application Tagging for Venafi Cloud

---

pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go

This makes it easier for users of the vcert library to distinguish between
temporary and permanent error conditions.
Signed-off-by: Richard Wall <richard.wall@jetstack.io>

Wrap all Authenticate errors with verror.AuthError

---

pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/tpp.go

Allows a vcert user to distinguish between errors caused by bad configuration
and temporary errors which may be resolved by retrying.
I also removed getURL and associated tests.
`baseURL` (a private field) will never be the empty because it is validated earlier in
`NewConnector`  via `normalizeURL`.

Wrap URL errors from tpp.NewConnector with verror.UserDataError

---

cmd/vcert/args.go
cmd/vcert/commands.go
cmd/vcert/flags.go
cmd/vcert/main_test.go
cmd/vcert/slices.go
cmd/vcert/utils.go
pkg/certificate/certificate.go
pkg/certificate/x509SubjectAltNameUPN.go
pkg/venafi/fake/connector.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/tpp.go

This code builds and tests successfully and exhibits the desired behavior when using the CLI.  The new `--san-uri` and `--san-upn` command line parameters have been left hidden from the CLI help because the project driving this does not require CLI support and because neither parameter is currently supportable by Venafi Cloud.

Add support UPN and URI SAN types for TPP

---

cmd/vcert/args.go
cmd/vcert/commands.go
cmd/vcert/flags.go
cmd/vcert/generate_test.go
cmd/vcert/result_writer.go
cmd/vcert/result_writer_test.go
cmd/vcert/validators.go
examples/simple-cli/main_test.go
go.mod
go.sum
pkg/certificate/certificateCollection.go

The follwing set of fixes provides the ability to generate the CSR and private key in json format.
Also fixes an issue with the enroll command and the json format when exported to multiple files (certificate, key, chain). The json structure was not generated correctly.

GitHub 114

---

cmd/vcert/flags.go
go.sum

The following fix provides the --file flag to the renew command, allowing it to be executed with --format pkcs12

Provide --file flag in renew command

---

cmd/vcert/result_writer.go

The following fix solves an issue where the csr is not being output in console or file when using --format pem

CSR not being output when using --format pem

---

cmd/vcert/result_writer.go

Fixes the pickup id serialization in the file. A key, value pair was being serialized, which is incorrect and breaks backwards compatibility. Change reverts back to only serialize the pickup id

Fix pickup id bad format

---

cmd/vcert/generate_test.go
pkg/venafi/tpp/connector_test.go

Some tests are failing because of the TLS renegotiation configuration not being setup for them.

Fixed an issue with tests failing because of the TLS renegotiation issue

---

cmd/vcert/args.go
cmd/vcert/flags.go
cmd/vcert/main_test.go
cmd/vcert/test_utils.go
cmd/vcert/utils.go
cmd/vcert/validators.go
pkg/certificate/certificate.go
pkg/util/constants.go
pkg/venafi/cloud/cloud.go
pkg/venafi/cloud/connector.go
pkg/venafi/cloud/connector_test.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go

Add the ability to specify validity when requesting a certificate
now use can request a certificate:
using tpp:
vcert enroll --u https://tpp.urlcom/ -t accesstken -cn abc.com -z zone --valid-days 4#M 
or using cloud:
enroll -k apikey -z zone -cn com.abc.com --valid-days 5#M
all test suite ran well.

Fix for: Add the ability to specify validity when requesting a certificate

---

cmd/vcert/args.go
cmd/vcert/commands.go
cmd/vcert/flags.go

- Hide `--client-pkcs12` from help since it is deprecated (was replaced by `--p12-file`)
- Remove `-z` and `--format` from revoke action (not applicable)
- Correct description for `--format` with getcred action

Hide deprecated parameters and fix inaccuracies in CLI online help

---

Makefile
README.md
cmd/vcert/generate_test.go
cmd/vcert/main_test.go
cmd/vcert/validators.go
pkg/venafi/tpp/connector_test.go

This PR attempts to address the issues reported in #134 . For this fix, I also included some minor updates to the docs to indicate all the environment variables that should be set when running 'make tpp_test'. I also added some new tests for the cmd package and added an option to the makefile to be able to run those tests with make. Finally, I fixed a broken test in the cmd package where the path separator was missing from a call to create a local file.
I am not setup to run cross-platform tests across all 3 platforms and the only test I am unable to execute successfully is Test_GetCertificateList in pkg/venafi/tpp due to not having a system with a large enough list of certificates in a single policy folder to test against. Other than these comments, all TPP tests pass on Linux as well as …

Fixes for issue #134 and fixing tests

---

pkg/venafi/tpp/connector.go

for tpp case  when converting hours to days, if the result have fractional numbers then round the final result(number of days with fractions) to the next integer
for example if the number of hours is 50 then 55/24 =2.2916666667, then it will be rounded to 3.

Round number of days on validity days for tpp

---

Makefile

Address issue with some web browsers and direct download of executable files
Standardize on "vcert" as the command to invoke regardless of the version or operating system
Remove build number from release asset names as requested by https://github.com/Venafi/vcert/issues/145

Release assets in zip archives with no build number in file names

---

aruba/features/format/jks.feature
aruba/features/format/pkcs12.feature
cmd/vcert/args.go
cmd/vcert/commands.go
cmd/vcert/flags.go
cmd/vcert/passwords.go
cmd/vcert/result_writer.go
cmd/vcert/result_writer_test.go
cmd/vcert/utils.go
cmd/vcert/validators.go
go.mod
go.sum

This PR is for the code to provide the support to format the output of the certificate, private key and the chain of trust to JKS similar to the behavior when the format to export is PKCS12.
In accordance of the Java Key Store specification, it's required a password to protect the Java Key Store, also it's required a password to protect the entry that will contain the certificate, private key and the chain of trust, and an alias for that entry.
So given the previous explanation, following the rules which are implemented in the current PR:
- User requests a **Java Key Store** by specifying _"jks"_ after the _-format_ switch
- User must use the _-file_ switch to specify the name of the keystore file when they specify _-format jks_.
- User specifies the password for the **store file and the …

Vcert jks support

---

Makefile
aruba/features/cred/cred.feature
aruba/features/credmgmt/credmgmt.feature
aruba/features/step_definitions/actions.rb
aruba/features/step_definitions/my_steps.rb
cmd/vcert/args.go
cmd/vcert/commands.go
cmd/vcert/config.go
cmd/vcert/flags.go
cmd/vcert/main.go
cmd/vcert/main_test.go
cmd/vcert/passwords.go
cmd/vcert/result_writer.go
cmd/vcert/usage.go
cmd/vcert/validators.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/search.go
pkg/venafi/tpp/tpp.go

This PR adds the functionality requested by https://github.com/Venafi/vcert/issues/150 and https://github.com/Venafi/vcert/issues/151 via new `checkcred` and `voidcred` actions.
```
vCert: 2021/01/24 23:01:21 Getting credentials...
access_token:  KIKro8hL/4EvvSeVuJQVlw==
access_token_expires:  2021-04-24T23:01:23Z
refresh_token:  PqIQ+4KAEFHGkHZM95b3og==
#
vCert: 2021/01/24 23:01:43 Checking credentials...
access_token_expires:  2021-04-24T23:01:22Z
grant_expires:  2022-01-24T23:01:22Z
client_id:  vcert-cli
scope:  certificate:manage,revoke
#
vCert: 2021/01/24 23:02:02 Access token grant successfully revoked
```

Adding checkcred and voidcred actions to VCert CLI

---

pkg/venafi/cloud/cloud.go

Added status 404 not found  to the cases for a zone not being found.
This is important for AWS plugin to be able to run its test successfully.

404 http status added

---

cmd/vcert/commands.go
cmd/vcert/flags.go
cmd/vcert/validators.go

Feedback from the release candidate was that the help wasn't clear about whether or not to escape the backslash in the `--z` value.  This is because that behavior varies by operating system and shell.  Given that policy folder DNs in TPP and application names and CIT aliases in VaaS often include spaces, I updated the help to show the zone value being surrounded in double quotes.  I also was more explicit about the actual zone value in the examples since we have them for both TPP and VaaS.

Rebranding Venafi Cloud to VaaS

---

pkg/venafi/cloud/connector_test.go
pkg/venafi/tpp/connector_test.go
test/fixtures.go

change the name of environment variables to be coherent with other Vcert implementation 
changes to use "management" folder for policy management tests

Minor changes policy management

---

pkg/policy/constants.go
pkg/policy/policyUtils.go
pkg/venafi/cloud/connector.go
pkg/venafi/tpp/connector.go

when user specify a wrong zone on cloud, vcert fails, the wrong zone is in format like "abbcd", so the parser can't get the cit value and instead get null, so validated that when the name is parsed we get an array size=2
fixed an issue when zone name in policy that contains all DN path but not \ at the beginning fails
test suite ran well

policy management bug fixes

---

pkg/policy/policyUtils.go

when subject altName -> dnsAllowed is true then policy creation/update is not allowed, this is a bad behavior, so fixe this to allow policy creation.

fix wrong validation on dnsAllowed policy attribute

---

pkg/venafi/tpp/connector.go
pkg/venafi/tpp/tpp.go

Potential fix for "vCert defaults to Server Certificate Type in TPP regardless of Certificate Template used" https://github.com/Venafi/vcert/issues/183
PS: I have tried the change and it works. However, I have not ran the tests :) I don't have environment.

Allow TPP to autodetect the type of certificate objects

---

cmd/vcert/args.go
cmd/vcert/commands.go
cmd/vcert/flags.go
cmd/vcert/result_writer.go
cmd/vcert/utils.go
cmd/vcert/validators.go
pkg/certificate/certificate.go
pkg/endpoint/endpoint.go
pkg/util/sshKeyGenerator.go
pkg/venafi/cloud/connector.go
pkg/venafi/fake/connector.go
pkg/venafi/tpp/authenticationError.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/sshCertUtils.go
pkg/venafi/tpp/tpp.go

The PR contains changes which will make vCert comparable with SSH Protect 21.4 and prior. The high-level changes are:
- Ability to consume the issued certificates returned as response of the SSHCertificate/Request API method.
- Fix the logic which handles errors returned by SSH Protect.
- Ability to store CA public keys to file using '--file' flag.
- '--no-prompt' flag will be considered when asking to overwrite existing files (--file flag). When the flag is used, it will overwrite the existing files.
- '--id' (Key ID) is not required anymore as SSH Protect may have default value. This works for both SSH Protect 21.3 and 21.4
/- /nolint added to some methods to prevent failed builds. This will be discussed with the maintainer.
PS: Apologues for the previous PR.

Changes to handle SSH Protect 21.4 (Updated)

---

aruba/features/enroll/enroll-with-csr.feature
aruba/features/step_definitions/my_steps.rb
cmd/vcert/commands.go
cmd/vcert/flags.go
cmd/vcert/result_writer.go
cmd/vcert/utils.go
cmd/vcert/validators.go
listener.go
pkg/certificate/certificate.go
pkg/certificate/certificateCollection.go
pkg/certificate/certificateCollection_test.go
pkg/certificate/certificate_test.go
pkg/endpoint/endpoint.go
pkg/util/pemUtil.go
pkg/util/sshKeyGenerator.go
pkg/util/utils.go
pkg/venafi/cloud/connector.go
pkg/venafi/fake/connector.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/search.go

VCERT Transition from PKCS1 to PKCS8 
Now private key are generated in PKCS8 format on csr local option.
format=legacy-pem was added so user can use this for generating PKCS1 key format on csr local option.
warning, for TPP user need to select one of the following private key PBE algorithms: SHA 3DES or SHA256 AES256

From pkcs1 to pcks8

---

pkg/certificate/certificate.go
pkg/certificate/x509SubjectAltName.go

Although it is primarily the responsibility of the issuing CA, for some use cases where the CA honors what has been requested in the CSR it is necessary to mark the SAN extension critical when there is no Subject so the issued certificate is compliant with [RFC 5280 Section 4.1.2.6](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.6).  In order to accomplish this we must construct the SAN extension ourselves and add it to the crypto/x509 CertificateRequest object rather than making use of the "helper" properties that usually simplify the task of adding SANs to a certificate request.  We were already doing that when we needed to add user principal name (UPN) SANs to a certificate request since they're not supported by the crypto/x509 package.

Fix for subjectless CSRs not complying with RFC 5280

---

cmd/vcert/commands.go
cmd/vcert/flags.go
pkg/policy/policyUtils.go
pkg/venafi/cloud/cloud.go

on policy specification now user can disable Subject fields by sending and empty array, i.e.: 
` "states": [ "" ] `

implement disabling subject fields.

---

aruba/features/credmgmt/credmgmt.feature
aruba/features/step_definitions/my_steps.rb
cmd/vcert/commands.go
pkg/venafi/tpp/tpp.go

I need to get the refresh-token expiry time when I interact with the TPP `Authorize/OAuth` and `Authorize/Token refresh` endpoints.
https://docs.venafi.com/Docs/21.4SDK/TopNav/Content/SDK/AuthSDK/r-SDKa-POST-AuthorizeOAuth.php
https://docs.venafi.com/Docs/21.4SDK/TopNav/Content/SDK/AuthSDK/r-SDKa-POST-AuthorizeToken.php
So I've added that value to the REST API response type and also modified `vcert getcred` to print the value.
Tested with a TPP 21.2 server as follows:
```console
$ make  build_quick cucumber FEATURE=./features/credmgmt/credmgmt.feature
...
8 scenarios (2 skipped, 6 passed)
61 steps (11 skipped, 50 passed)
0m10.152s
```
I have not tested this with PKCS12 client-cert nor with VaaS.

Include the refresh_until value in the output of vcert getcred

---

pkg/endpoint/endpoint.go
pkg/venafi/cloud/connector.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/tpp.go

Both TPP and VaaS can support situations where multiple policies have been defined for use by a single consumer.  For TPP, this is done by creating multiple child policy folders in a common parent policy folder.  For VaaS, this is done by assigning multiple Issuing Templates to a single application.  The new `GetZonesByParent` methods for TPP and VaaS allow VCert client SDK consumers to enumerate those policies (zones) rather than having to know them individually.

Get policies for zone prefix

---

pkg/venafi/tpp/connector.go

Linter is throwing error G601: Implicit memory aliasing in for loop.

Fix linter err G601

---

pkg/policy/policyStructures.go
pkg/venafi/cloud/cloud.go
pkg/venafi/cloud/connector.go

The Org Unit construct was dropped from Venafi as a Service last week and since then the `setpolicy` action has not worked.  This update addresses that and informs the user if there was a problem creating applications (previously the output made it seem as though it was successful when it wasn't).

Fix policy management for VaaS after Org Unit removed

---

.gitignore
Makefile

- Adds commands to collect Linux and Darwin signatures during artifact process
- Adds vendor folder to git-ignore file

Signing Linux and Darwin binaries. Gitignores vendor

---

pkg/venafi/cloud/connector.go

VCert recently added support for VaaS headless registration but that user can't immediately begin requesting test certificates after they've registered because a VaaS application is required.  They could accomplish this by logging into the VaaS UI or use the `setpolicy` action but that is an undesirable extra step and the latter assumes they have administrative access to VaaS.  To simplify things and meet the objective of headless registration, VCert will be enhanced by this PR to automatically create VaaS applications if they are for the Default issuing template.  As such a new user would only need to invoke two actions to obtain a test certificate, `getcred` and `enroll`:
```
vcert getcred --email zach.jackson@venafi.example
vcert enroll -k xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -z …
```

Auto-create VaaS apps for headless registration

---

aruba/features/renew/renew-with-csr-service.feature
aruba/features/step_definitions/actions.rb
aruba/features/step_definitions/openssl.rb

- Adds missing logic in aruba test cases to handle passphrases dynamically for `renew` method for service generated csr test suite
- Adds corresponding `--no-prompt` use case for previous mentioned test suite

Fix renew pkcs12 - 1

---

pkg/endpoint/endpoint.go

This PR fixes #242 by changing the term 'expessions' to 'expressions' in 9 places under the [endpoint.go ValidateCertificateRequest function](https://github.com/Venafi/vcert/blob/d93c827148a14d344893d71cf34e3fad3d22fa74/pkg/endpoint/endpoint.go#L216)

Updated misspelled term 'expessions' in 9 places

---

Makefile

compress signatures inside the releases zip files that were missing in the code-sign process

compress signatures inside the releases zip files

---

pkg/certificate/certificate.go
pkg/certificate/certificate_test.go
pkg/endpoint/endpoint.go
pkg/util/utils.go
pkg/venafi/cloud/connector.go
pkg/venafi/cloud/connector_test.go
pkg/venafi/cloud/search.go
pkg/venafi/cloud/search_test.go
pkg/venafi/fake/connector.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/search.go
pkg/venafi/tpp/search_test.go
pkg/verror/errors.go

A function was added for both TPP and VaaS that enables searching for a valid certificate.
```go
SearchCertificate(zone string, cn string, sans *certificate.Sans, valid_for time.Duration) (*certificate.CertificateInfo, error)
```
If it returns no error, the certificate returned should be the latest [1] exact matching **zone** [2], **CN** and **sans.DNS** [3] provided
[1] the one with longest validity; field named **ValidTo** for TPP and **validityEnd** for VaaS
[2] application name for VaaS
[3] an array of strings representing the DNS names
It should address https://github.com/Venafi/vault-pki-backend-venafi/issues/102, preventing duplicate certificates

Search valid certificate

---

pkg/venafi/cloud/connector.go
pkg/venafi/cloud/search.go
pkg/venafi/cloud/search_test.go

Currently, if you pass an empty CN, an empty SANS object or empty SANS.DNS parameter the search request will fail with a server error, since an empty parameter is being added to the search request.
This pull request adds the capability to send an empty CN or SANS.DNS to the search function and the necessary tests to ensure the parameters are being removed or passed depending on the situation..

Allow empty CN/SANS in Cloud/VaaS certificate search

---

client.go
cmd/vcert/utils.go
cmd/vcert/validators.go
listener.go
pkg/certificate/certificate.go
pkg/certificate/certificateCollection.go
pkg/endpoint/endpoint.go
pkg/policy/policyUtils.go
pkg/util/pemUtil.go
pkg/venafi/cloud/cloud.go
pkg/venafi/cloud/cloudUtil.go
pkg/venafi/cloud/company.go
pkg/venafi/cloud/connector.go
pkg/venafi/cloud/connector_test.go
pkg/venafi/fake/fake.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/tpp.go
vcert.go

Since Go 1.19, the go code formatter also formats comments.
This PR formats all source code.
This will prevent contributors that use go 1.19+ from contributing unrelated formatting changes in the future.

run 'go fmt ./...' using go 1.19.2

---

pkg/venafi/tpp/connector_test.go

There are no tests that would allow us to "see" and discuss the issue reported in  https://github.com/Venafi/vcert/issues/171. Having tests, even statically mocked HTTP ones, would also allow us to prevent breakage (as much as possible) when changing RetrieveCertificate in #269.
I used `curl` and a 20.1 TPP VM to capture each individual HTTP response. At some point, I wish to document further how I produced these response samples.
The reason I went for a mocked HTTP server is because making the live TPP server return all of these messages is tricky; most 500 errors aren't easily reproducible unless we set up the e2e TPP VM to have e.g. one of its CA templates broken on purpose.
This "mocked HTTP server" approach isn't ideal because a drift may appear between earlier versions of TPP and …

RetrieveCertificate: add mocked HTTP tests using real TPP responses

---

pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/tpp.go

**Update 29 Nov 2022:** I put this PR back to "draft" because I am less and less confident with the changes I am making here. I propose to first agree on a set of `RetrieveCertificate` tests in #270 before I make any change to it `RetrieveCertificate`. When we have merged #270, we can proceed with the current PR.
**Update 5 Dec 2022:** I am now confident with the PR, it can now be reviewed.
---
**The problem:** When enrolling a new certificate, for example by running `vcert enroll` or when using cert-manager, people get "stuck" with an error of the like:
500 Certificate \VED\Policy\Test\foo.com has encountered an error while processing,
Status: This certificate cannot be processed while it is in an error state. Fix any
errors, and then click Retry., Stage: 700.
This message occurs when a …

Change RetrieveCertificate so that it resets the enrollment (if it exists) while retrieving the certificate

---

pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/tpp.go

This reverts commit 240fe8ff3ae0a85b998804665cc7f1400ea6b210, reversing changes made to e607e3078c059a6e4c388bd96af5f7c3cb55d613.
In https://github.com/Venafi/vcert/pull/269 we added a call to the TPP reset endpoint to reset a certificate in case a new CSR is submitted and the old certificate was in an error state.
@maelvls found that there is a race condition in TPP (https://github.com/Venafi/vcert/issues/273) that results in the reset action removing the newly requested CSR, making TPP incorrectly fallback to the previous CSR that was submitted.
Since this behaviour further complicates debugging a situation in which an error occurs, we want to revert this commit.
⚠️This is an urgent bug fix and that anyone using 4.23.0 will want to update!
CC @achuchev

Revert "Merge pull request #269 from maelvls/reset-before-request"

---

Makefile

Many dev's are using containers running on M1/2 Macs these days so it's useful to have a suitable binary.

Adds Support for Linux ARM

---

cmd/vcert/commands.go

This changes fix current (v1.51) golangci-lint issue:
```
golangci-lint run
cmd/vcert/commands.go:231:34: G402: TLS InsecureSkipVerify set true. (gosec)
tlsConfig.InsecureSkipVerify = true
```

Fixing linter issue

---

pkg/venafi/tpp/tpp.go
pkg/venafi/tpp/tpp_test.go

In TPP, we are used to specifying ".example.com" in the allowed domains, this restriction matches all subdomains of example.com, without matching example.com itself.
vCert does however not translate this rule into regex correctly, causing errors like the following:
```
Failed to request venafi certificate: common name test.example.com is not allowed in this policy: [^([\p{L}\p{N}-*]+\.)*\.example\.com$]
```
This PR fixes the regex generation logic and adds a test for this fix.

Fix regex domain name validation

---

cmd/vcert/utils.go
pkg/certificate/certificate.go
pkg/util/constants.go
pkg/venafi/cloud/connector.go
pkg/venafi/cloud/connector_test.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go

From: https://github.com/Venafi/vcert/pull/285
> The current ValidityHours option is too limiting when using VCert as a Go library.
> Instead, I introduced the ValidityDuration option in this PR.
> This option:
> - allows creating certificates that are valid for:
>   - < 1day (currently not supported in combination with TPP)
>   - < 1hour (currently not supported in combination with TPP & VaaS)
> - adds a new option "ALL_ISSUERS" to the `issuerHint`; when you use this option, all known issuer-specific "Specific End Date" attributes will be send to TPP.
Doing this PR as other one #285 got on bad state due to rebase.

Adds ValidityDuration in favor of deprecating ValiditityHours

---

pkg/venafi/cloud/cloud.go

Currently, I get the following errors in case I'm using an invalid API key for VaaS:
```console
$ vcert enroll -k xxxxxxxx-xxxx-xxxxx-xxxxxx-xxxxxxxxxx -z "a\a" --cn dd
Enter key passphrase:
Verifying - Enter key passphrase:
vCert: 2023/06/15 15:51:02 Unable to connect to Venafi as a Service: vcert error: server error: invalid character 'I' looking for beginning of value
vCert: 2023/06/15 15:51:02 vcert error: must be autheticated to retrieve certificate
$ vcert enroll -k aa -z "a\a" --cn dd
Enter key passphrase:
Verifying - Enter key passphrase:
vCert: 2023/06/15 15:51:10 Unable to connect to Venafi as a Service: vcert error: server error: unexpected end of JSON input
vCert: 2023/06/15 15:51:10 vcert error: must be autheticated to retrieve certificate
```
This PR makes it so the user …

Provide user with useful error message in case VaaS API Key is invalid

---

pkg/venafi/tpp/connector.go
pkg/venafi/tpp/search_test.go
pkg/venafi/tpp/tpp.go

In TPP, the ObjectDN value is built using either the FriendlyName or the CommonName (if no FriendlyName is provided).
During processing Location, VCert logic incorrectly assumes that the object DN is always based on the CommonName.

Bugfix: updates processing Location to handle FriendlyName

---

pkg/endpoint/endpoint.go
pkg/venafi/cloud/connector.go
pkg/venafi/fake/connector.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/tpp.go

https://github.com/Venafi/vcert/pull/274 has shown that it is very hard to find an auto-reset solution that works for all usecases.
For this reason, I propose that we add a low level ResetCertificate function which can be called only on the TPP Connector.
This function exposes a low-level endpoint to client libraries who want to use this functionality.

Add reset TPP endpoint

---

pkg/certificate/certificate.go
pkg/certificate/certificate_test.go
pkg/endpoint/endpoint.go
pkg/endpoint/endpoint_test.go
pkg/venafi/cloud/certificatePolicies.go
pkg/venafi/cloud/cloud.go
pkg/venafi/cloud/cloud_test.go
pkg/venafi/cloud/connector_test.go
pkg/venafi/tpp/tpp.go

Summary:
- The KeyCurve value was left empty in `NewRequest` for `ecdsa.PublicKey`s, this was marked as a TODO item in the code.
- This PR adds code to set the ED25519 `local` generated CSR support for VaaS
- Adds a test for this `NewRequest` function.
- Added a switch case that sets KeyType for ed25519 keys.
EDIT: This PR does the above but support for ED25519 Keys are only available for local generate CSR's and, only supported by VaaS, so we have set up validation for any use related to TPP, since TPP doesn't support ED25519 keys for any of the supported methods. Also we have made necessary changes for this Keys, as they are using another type of algorithm different from ECDSA, there's a validation we do in:
`func (request *Request) CheckCertificate(certPEM string) error {`
that …

NewRequest: set KeyCurve in NewRequest and add support for ed25519 for local CSR on VaaS

---

pkg/endpoint/endpoint.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go

I missed this in https://github.com/Venafi/vcert/pull/295.
This PR fixes the IsCertNotFound function and ensures that it keeps working by using it in our test.

Fix bug in IsCertNotFound function & add use function in test

---

pkg/playbook/app/domain/playbookRequest.go
pkg/playbook/app/installer/capi.go
pkg/playbook/app/installer/installer.go
pkg/playbook/app/installer/jks.go
pkg/playbook/app/installer/pem.go
pkg/playbook/app/installer/pkcs12.go
pkg/playbook/app/service/service.go
pkg/playbook/app/vcertutil/vcertutil.go

Also:
- Removed unnecessary interface functions in installer.go 
- Removed unused arguments from Installer interface functions
Closes VC-25405

Added encryption to Private Key for PEM installer

---

pkg/playbook/app/domain/authentication.go
pkg/playbook/app/parser/writer_test.go
pkg/playbook/app/vcertutil/vcertutil.go
test-files/playbook/sample.yaml

Adds support to Firefly certificate enrollment in VCert Playbook. 
An Access Token must be provided in credentials
Closes VC-25641

feat(firefly): Add support for Firefly in VCert Playbook

---

cmd/vcert/validators.go

Now the error message when Firefly zone is not set is referring to Firefly instead of TPP.

Feat: Fix error message for missing firefly zone

---

cmd/vcert/commands.go

Replacing the `--token-url` appearence by the `-u` parameter in the `getcred` description

Feat: Update getcred description

---

cmd/vcert/playbook.go
cmd/vcert/playbook_test.go

Fix issue where certificate authentication was trying to use the `request.keyPassword` value instead of the update `installation.p12Password`.  Includes updates to tests and validated.

Fix p12Task using incorrect password

---

pkg/playbook/app/installer/capi.go
pkg/playbook/util/capistore/embedded/install-cert.ps1

Fixed 2 issued found during testing:
1. CAPI Installer Check() function had a logic bug and was checking the wrong variable to determine if it should fall back to deprecated behavior.
2. Error in the actual CAPI Install script, causing the root and intermediate certificate to be installed in the "My" store all the time. (This will cause unintended results on Windows)

More CAPI fixes following testing

---

pkg/playbook/app/domain/error.go
pkg/playbook/app/domain/installation.go
pkg/playbook/app/installer/capi.go
pkg/playbook/app/installer/installer.go
pkg/playbook/app/installer/jks.go
pkg/playbook/app/installer/pem.go
pkg/playbook/app/installer/pkcs12.go
pkg/playbook/app/service/service.go
pkg/playbook/app/vcertutil/vcertutil.go
pkg/playbook/util/capistore/embedded/install-cert.ps1

- Added capiFriendlyName field to installation object 
- Added capiLocation field to installation object
- Deprecated location field from installation object
- Added warning when using deprecated location field 
- Added warning when capiFriendlyName is not set
- Now CAPI installations will use the value set in `capiLocation`. If not set, then will use the value from `location`
- CAPI installations will use the value set in `capiFriendlyName`. If not set, then will use the value from the `request.subject.commonName` (Check) or `certificate.subject.commonName` (install)
- A random password will be generated for the P12 bundle used to import the certificate into CAPI store every time a certificate is installed

feat(playbook): Added attributes to CAPI installation

---

examples/playbook/sample.capi.yaml
examples/playbook/sample.jks.yaml
examples/playbook/sample.multi.yaml
examples/playbook/sample.pem.yaml
examples/playbook/sample.pkcs12.yaml
examples/playbook/sample.tlspc.yaml

1. Updated playbooks with the **state** field in the request section (replacing **province**) as per (https://github.com/Venafi/vcert/blob/master/README-PLAYBOOK.md#subject)
2. Updated the TLSPC example to use a ENVVAR for the APIKEY

Replaced province with state in request section

---

aruba/Dockerfile
aruba/features/playbook/steps_definitions/my_steps.rb
aruba/features/step_definitions/openssl.rb

- Adds legacy support for PKCS12. E2E tests don't work on newer docker images because of new Open SSL that dropped support by default, adding flag to restore the support). This fixes:
```
vcert enroll -u '' -k **** -z 'redacted'  -cn 1my-test.example.com -format pkcs12 -file all.p12 -key-password ****
openssl pkcs12 -in "all.p12" -passin pass:*** -noout
Error outputting keys and certificates
40A71564917F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```
- Constrain Ruby image version to `ruby:3.2`. This is so we don't get any surprise eventually due issue mentioned happened above.

Minor fixes for VCert e2e inorder to work with latests images

---

cmd/vcert/validators.go

When it comes to generating CSRs with SANs, VCert is much easier than OpenSSL.  Currently you can only generate a CSR using the `gencsr` action if you specify either a CN or DNS SAN.  This restriction exists because public CAs commonly have such a requirement and specifying a CN is best practice to give certificates a primary identifier.  Modern use cases, such as those using SPIFFE, typically request certificates with no subject and only a single URI SAN (i.e., the SPIFFE verifiable identity document, SVID).  I've made this small update to VCert CLI so that it is possible to generate certificates like this for testing with Venafi Firefly and enterprise PKIs supporting modern use cases.

Align gencsr input validation with standards

---

pkg/venafi/fake/ca.go

As our pipeline updated to version of golangci-lint: 1.55.1, now it identified our fake hardcoded credential. We need to let know the linter it can safely be ignored, since is not a valid credential and we just use it for testing.

fix: lint issue with hardcoded credentials

---

pkg/venafi/tpp/connector_test.go

This PR should be merged before continuing reviews on #418.
I paused working on #418 so that I could write some unit tests around `getIdentity` with the existing implementation (the one in the master branch). Once we have the unit tests merged to master, we can resume working on #418.
I could have added all of these tests directly to #418, but we wouldn't be sure whether the old implementation and the new implementation pass the same tests.
This way, we can decrease the chance of introducing a regression in `getIdentity`.
To know more about the tricks that `getIdentity` does, you can read https://github.com/Venafi/vcert/pull/221#issuecomment-1911747389.

Contact Emails: Add unit tests for `getIdentity`

---

pkg/certificate/request.go
pkg/policy/policyStructures.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/tpp.go

To be considered:
- I wrote an end-to-end test but it will fail on VCert's TPP test instance https://supertreat.venqa.venafi.com/ because this instance only has local users, but this feature requires TPP to be configured with LDAP or AD. I'm not sure how to proceed with this.
- The func `RequestCertificate` now requires the scope `configuration` when ~`ContactEmails`~ `Contacts` is used. I don't think that's a big deal as long as we indicate it in the Go struct's documentation as well as above the RequestCertificate func.
Regarding the new ~`ContactEmails`~ `Contacts` field that I propose on the Request struct, I thought about making it more generic to allow for using an ID in the future (corresponding to the prefixed universal in TPP or a UUID in TLSPC) but since I could not find a …

Contact Emails: RequestCertificate can now be given contact emails

---

pkg/certificate/request.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/tpp.go

In order for other integrations to consume and override enrollment timeout. We enable `WorkDoTimeout` in order to override TLSPDC (TPP) default CA timeout (60secs). To be noted that as of now, maximum value is 120 seconds. If greater value is provided (e.g. 180 secs), TPP will automatically take 120 secs.

Enables WorkToDoTimeout for certificate request

---

cmd/vcert/args.go
cmd/vcert/commands.go
cmd/vcert/config.go
cmd/vcert/datareader.go
cmd/vcert/envVars.go
cmd/vcert/flags.go
cmd/vcert/main.go
cmd/vcert/validators.go
cmd/vcert/validatorsCloud.go
cmd/vcert/validatorsFirefly.go
cmd/vcert/validatorsTPP.go
pkg/venafi/cloud/connector.go
pkg/venafi/cloud/oauth.go

feat(svc-account-cli): Adds support for TLSPC service account authentication in vCert cli

---

client.go
client_test.go
config.go
examples/firefly/main.go
examples/server/main.go
examples/simple-cli/main.go
examples/tlspc-svc-account/main.go
go.mod
go.sum
pkg/endpoint/endpoint.go
pkg/util/constants.go
pkg/venafi/cloud/cloud.go
pkg/venafi/cloud/connector.go
pkg/venafi/fake/connector.go
pkg/venafi/firefly/connector.go
pkg/venafi/firefly/firefly.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/tpp.go

**Software like cert-manager can now supply its own User-Agent when it instantiates the vcert.Client.**
> Why? Because if there is a bug in the cert-manager Venafi issuer, which causes it to not back off in the event of a failed API request, the Venafi server administrator can quickly know that cert-manager is the culprit and quickly report the bug so that it be quickly fixed.
**The default User-Agent for `vcert` CLI and for any software importing the vcert/v5 is now: `vcert/v5`.**
> Why? Because right now the vcert CLI and any software that uses the vcert SDK will use the [default `Go-http-client/1.1` User-Agent header](https://github.com/golang/go/blob/db423dde85ad4923c2c4addb1cd96f119c7b6dc6/src/net/http/request.go#L534-L538) and the requests will be indistinguishable from any other Go …

[VC-31275] Allow user to configure the User-Agent HTTP header in vcert SDK

---

pkg/playbook/app/domain/connection.go

Optimizes playbook VCP credentials validation. Courtesy of @sbanic-venafi

fix(playbook): Minor optimization of code

---

pkg/venafi/cloud/connector.go

For the VaaS integration, vcert unconditionally calls the DEK API endpoints.
Similarly to the TPP implementation, we can only call the DEK API calls when a ServiceGeneratedCSR is requested.
This reduces the number of API requests made by vcert.
See the TPP equivalent of this check: https://github.com/Venafi/vcert/blob/21228d0e0de959feddf95acb7d7a22402e2edd23/pkg/venafi/tpp/connector.go#L1359-L1365

Only call DEK endpoints if the CSR is a ServiceGeneratedCSR

---

pkg/venafi/cloud/certificatePolicies.go
pkg/venafi/cloud/cloud_test.go

The `addStartEndToArray` function was missing for the `p.IpSanRegExs` `p.EmailSanRegExs` `ct.SanRfc822NameRegexes` and `ct.SanUniformResourceIdentifierRegexes` fields.
`addStartEndToArray` also changed the policy because it created an empty slice for a nil input (instead of just returning nil instead).

BUGFIX: cloud toPolicy SAN regex processing

---

pkg/venafi/cloud/connector.go

Fixes an issue whereby graphql client for cloudproviders was only initialized with api key authentication

fix(cloud-provisioning): Fixes graphql client initialization in cloud connector

---

pkg/domain/cloudproviders.go
pkg/venafi/cloud/cloudproviders.go
pkg/venafi/cloud/connector.go
pkg/webclient/cloudproviders/cloudproviders.gen.go
pkg/webclient/cloudproviders/cloudproviders.go
pkg/webclient/cloudproviders/genqlient.graphql

Adds cloud provider name to cloud keystore query

Cloud keystore query fix

---

cmd/vcert/cmdCloudKeystores.go
cmd/vcert/flags.go
cmd/vcert/result_writer.go
cmd/vcert/validators.go

- Adds implementation to output to file for provisioning in CLI
- Fixes pickup-id-file validations

Adds implementation to output to file for provisioning in CLI

---

cmd/vcert/cmdCloudKeystores.go
cmd/vcert/utils.go
examples/provisionWithCertificateRequest/main.go
examples/provisionWithServiceAccount/main.go
pkg/domain/provisioning.go
pkg/venafi/cloud/cloudproviders.go

- fixes bug where wrong pickup-id variable was set. 
- fixes bug for ARN as the value from websocket is not responding with that value. Thus this required update in function provisionToMachineIdentiy to find out before hand the keystore type (if keystore was not provided in request

BUG FIX: issue with pickup-id flag and ARN in response when provisioning to AWS

---

.gitignore
aruba/Dockerfile
aruba/Gemfile
aruba/cucumber.sh
aruba/features/playbook/steps_definitions/my_steps.rb
aruba/features/provision/cloudkeystore/provision_cloudkeystore.feature
aruba/features/provision/cloudkeystore/steps_definitions/my_steps.rb
aruba/features/step_definitions/actions.rb
aruba/features/step_definitions/endpoints.rb
aruba/features/step_definitions/my_steps.rb
aruba/features/support/aruba.rb
aruba/features/support/google_provider.rb
cmd/vcert/validators.go

- Adds Google Provider basic cucumber test
- Adds GCM client to delete certificate afterward
- Removes unused gemfile
- updates pickup-id validators to proper variable

VC-32829 / Adds GCP cucumber tests for provisioning

---

pkg/venafi/cloud/connector.go

Adds certificate ID to certificate request object on cloud connector certificateRetrieve function when not requesting the private key

fix(cloud-connector): Adds certificate ID

---

README-CLI-CLOUD.md
aruba/Dockerfile
aruba/cucumber.sh
aruba/features/provision/cloudkeystore/provision_cloudkeystore.feature
aruba/features/provision/cloudkeystore/steps_definitions/my_steps.rb
aruba/features/support/aruba.rb
aruba/features/support/aws_provider.rb
aruba/features/support/google_provider.rb
cmd/vcert/args.go
cmd/vcert/cmdCloudKeystores.go
cmd/vcert/flags.go
cmd/vcert/result_writer.go
cmd/vcert/utils.go
examples/provision/main.go
pkg/domain/provisioning.go
pkg/venafi/cloud/cloudproviders.go

- Changes output in CLI to unify returned ID's from providers in Cloud ID. 
- Provides ability to provider ARN in VCert SDK, and as well we add ARN flag in VCert CLI. 
- Adds AWS Cloud Provider testing for provisioning in cucumber tests and also refactors code accordingly. 
- Adds AWS client to delete certificate after certificate is provisioned afterward

VC-32829 / Adds AWS cucumber tests for provisioning

---

.golangci.yml
pkg/endpoint/endpoint.go
pkg/util/pemUtil.go
pkg/venafi/cloud/cloudUtil.go
pkg/venafi/cloud/connector.go
pkg/venafi/cloud/search.go
pkg/venafi/firefly/connector.go
pkg/venafi/tpp/connector.go
pkg/venafi/tpp/sshCertUtils.go

- Fixes warning from GolangCI-Lint that states that configurations: "deadcode" and "varcheck" are deprecated and deactivated. Removes from GolangCI Lint configuration accordingly.
- Fixes following lint rules:
- SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
- printf: non-constant format string in call to fmt.Errorf (govet)

Fixes lint error issues and golangci deprecated configurations

---

examples/ansible/README.md
examples/ansible/oauth2.ADFS_clientcredentials.yaml
examples/ansible/oauth2.Auth0_clientcredentials.yaml
examples/ansible/oauth2.AzureEntra_clientcredentials.yaml
examples/ansible/testvcertplaybook.yaml

Adding Sample Ansible playbooks that can be used to trigger [VCert Playbooks](https://github.com/Venafi/vcert/blob/master/README-PLAYBOOK.md) using Venafi Control Plane (VCP) [Service Accounts](https://docs.venafi.cloud/vcs-platform/serviceaccounts/about-service-accounts/). 
This method of execution allows for TLSPC svc accounts to be used without storing the credentials to authentication to the IDP on each VM, or setting up scheduled tasks on each managed VM. 
Contains:
- New Examples Folder for Ansible.
- folder README.md file explaining use case and requirements.
- Ansible playbook examples for Azure Entra, ADFS, and Auth0. 
- Example vcert playbook file.

Add examples for running playbooks with ansible while using TLSPC SVC accounts

---

.gitignore

Whenever we run any of the "make test_" there are coverage files that are generated. We don't need to keep track of those file

Adds Tests Generated Files to Gitignore

---

cmd/vcert/validatorsCloud.go

In https://github.com/Venafi/vcert/pull/453, the flag `--idp-jwt` was removed and replaced by `--external-jwt`, but some of the error messages still mention `--idp-jwt`. This PR fixes the error messages.

Fix some mentions to the removed `--idp-jwt` that was renamed to `--external-jwt`

---

pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/sshCertUtils.go

Since when we introduced the `workToDoTimeout` attribute to be set for TPP request in VCert, we have had some sporadic issues in tests with the following error:
```
[2024-11-21T09:44:32.149Z]     connector_test.go:2304: Unexpected status code on TPP Certificate Request.
[2024-11-21T09:44:32.149Z]          Status:
[2024-11-21T09:44:32.149Z]          202 Accepted. 
[2024-11-21T09:44:32.149Z]          Body:
[2024-11-21T09:44:32.149Z]         {
"CertificateDN": "\\VED\\Policy\\<redacted>\\redacted.example.com",
"Devices": [
{
"Applications": [
{
"DN": "\\VED\\Policy\\<redacted>\\instance\\workload-17redacted55"
}
],
"DN": "\\VED\\Policy\\redacted\\instance"
}
],
"Error": "Certificate processing took longer than WorkToDoTimeout. Call certificates\/retrieve to get the certificate data",
"Guid": …
```

Fixes test pipeline issue tpp

---

pkg/certificate/certificate.go
pkg/venafi/tpp/connector_test.go
pkg/venafi/tpp/tpp_test.go

This causes the `.ValidateCertificateRequest()` validation function to fail for 3072 bit RSA keys.

Add missing RSA 3072 bit key size

---

cmd/vcert/main.go
pkg/endpoint/endpoint.go

vCert sets a log prefix on the global logger in endpoint.go.
This unexpectedly alters the logger when importing vCert.
In order to not modify the global logger when importing vCert as a go library, I moved the `SetPrefix` call to `main.go` which is only used in the vCert binary but when importing vCert as a library.

Set log prefix in main.go instead of endpoint.go
